name: Python unittests

# This determines when the workflow runs
on:
  push:
    branches: [ "main", "dev" ] 
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Change this to the Python version you are using

    # 3. Install your project dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Create the assistant file from the example template
    - name: Create config from example
      run: cp app/config/assistant-template.yaml app/config/assistant.yaml

    # 5. Run your tests using the command you provided
    - name: Run tests
      run: |
        python -m unittest discover -s tests -v
